### ISSUE TITLE
tooltip flicker on top left corner when hiding

### ISSUE THREAD

**Issue by smontanari** [bumbeishvili/d3-v6-tip#2] opened 2020-12-30 12:12 UTC
I'm in the process of migrating my project to d3 version 6 and I was glad to see you had taken the time to continue to maintain the original `d3-tip` package by @caged.

Unfortunately I run into the following issue when using the new version of the tooltip: 
when invoking the `hide()` function (typically on a `mouseout` event) the tooltip briefly appears at the top left corner of the browser window, only to disappear instants later. This issue is a bit annoying and happens whenever there is enough room in the layout for the `mouseout` event to be triggered and processed (hence invoking the `hide()` function).

The original d3-tip version did not have this problem, and I noticed a difference in your implementation of the `hide` function with respect to that, where you explicitly set the position of the tooltip to the top left corner before setting the opacity, i.e.:
```javascript
nodel
    .style('top', 0)
    .style('left', 0)
    .style('opacity', 0)
    .style('pointer-events', 'none')
```

I'm not aware of the reasons for resetting the position of the tooltip, but it appears that the positioning takes precedence over the setting of the opacity, hence the flickering of the tooltip at the top left corner of the  document. I tried swapping the style instructions around, applying the opacity before the position, but with no success.
When instead I re-introduced the original code, removing the positioning altogether, the problem went away.

Would you consider the possibility of removing the position (re-)setting, or, at least, to make it configurable?

**Comment by bumbeishvili** [comment] 2020-12-31 07:47
@smontanari that piece of code was already included in the original repo, which I forked from
https://github.com/VACLab/d3-tip/blob/master/d3-tip.js#L65

I am using this lib  extensively in my projects and I haven't come across the same issue.

Can you provide a sample JSFiddle where this issue will be reproduced? 

You can extend this sample - https://jsfiddle.net/aftjeb0g/2/

**Comment by smontanari** [comment] 2021-01-02 01:39
Thanks @bumbeishvili for getting back to me. I troubleshooted the issue and I've tweaked your fiddle to re-create the problem. It's quite simple, actually: just apply a fading transition effect to the tooltip, which is what I was doing in my project.

Now, we can argue on whether using a fading effect is allowed or not. But if not, maybe it should be made very clear in the documentation, as it's not unusual to use such technique to make it a smoother UI.

However, I'd like to ask, again: what is the reason for setting the position of the tooltip at (0.0) when hiding? The [original code](https://github.com/caged/d3-tip) from @caged (not the code you linked me to) does not do that.
Alternative question: what happens if we remove that logic? Does it break anything in the expected tooltip behaviour?
Because, if not, I believe that is all is needed to fix this issue.

**Comment by bumbeishvili** [comment] 2021-01-02 23:17
> Now, we can argue on whether using a fading effect is allowed or not. But if not, maybe it should be made very clear in the documentation, as it's not unusual to use such technique to make it a smoother UI.

That's a good use case, and I agree with you, current behavior is not very smooth

> However, I'd like to ask, again: what is the reason for setting the position of the tooltip at (0.0) when hiding? The original code from @caged (not the code you linked me to) does not do that.

I have no idea, I just copied that code and fitted it to v6

> Alternative question: what happens if we remove that logic? Does it break anything in the expected tooltip behavior?
> Because, if not, I believe that is all is needed to fix this issue.

I am not sure, again

**Comment by bumbeishvili** [comment] 2021-01-02 23:21
I just saw checked git blame

<img width="817" alt="Screenshot 2021-01-03 at 03 18 45" src="https://user-images.githubusercontent.com/6873202/103468452-7a654600-4d72-11eb-9729-2d1acdb667c0.png">

There was not any specific issue associated with this commit, and since it was not in the original source code as well,  I'd say we can safely remove these two lines

**Comment by smontanari** [comment] 2021-01-03 02:13
I agree, and I like the fact that by removing those two lines the tooltip default behaviour would be kept simple and straightforward. 
And at some point (if requested) the functionality could always be extended to allow the injection of specific behaviour in those scenarios, such as re-positioning the tooltip.

**Comment by smontanari** [comment] 2021-01-06 22:04
do you need any help to close this issue? Happy to open a PR if you want me to

**Comment by bumbeishvili** [comment] 2021-01-07 05:03
PR would be appreciated Sent from my Galaxy
-------- Original message --------From: Silvio Montanari <notifications@github.com> Date: 1/7/21  2:04 AM  (GMT+04:00) To: bumbeishvili/d3-v6-tip <d3-v6-tip@noreply.github.com> Cc: David Bumbeishvili <dato.developer@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [bumbeishvili/d3-v6-tip] tooltip flicker on top left corner when hiding (#2) 
do you need any help to close this issue? Happy to open a PR if you want me to

**Closed** 2021-01-07 23:40 UTC

**Comment by bumbeishvili** [comment] 2021-01-07 23:46
Published - https://www.npmjs.com/package/d3-v6-tip
